[project]
name = "ms-procesamiento-ordenes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "kafka>=1.3.5",
    "kafka-python>=2.0.3",
]
